// JNI entry point for obsidian-media-player (ObsidianMediaPlayerSpec).
//
// The Fabric component descriptors for <ObsidianVideo> are generated by React
// Native Codegen from src/specs/NativeObsidianVideo.ts into:
//   android/build/generated/source/codegen/
// Those headers only exist for New Architecture builds, so every reference to
// them is guarded by __has_include. On the Old Architecture (Paper) this file
// compiles to a plain no-op entry point and <ObsidianVideo> works through the
// SimpleViewManager (ObsidianVideoManager.kt) as before.

#include <fbjni/fbjni.h>
#include <jni.h>

#if __has_include(<react/renderer/components/ObsidianMediaPlayerSpec/ComponentDescriptors.h>)
#include <react/renderer/componentregistry/ComponentDescriptorProvider.h>
#include <react/renderer/componentregistry/ComponentDescriptorProviderRegistry.h>
#include <react/renderer/components/ObsidianMediaPlayerSpec/ComponentDescriptors.h>

namespace facebook::react {

// Called by the app (or by DefaultComponentsRegistry wiring) to expose the
// generated <ObsidianVideo> descriptor to Fabric. Kept separate from
// JNI_OnLoad so Old Architecture runtimes never touch Codegen symbols.
void registerObsidianMediaPlayerSpecComponentDescriptors(
    std::shared_ptr<const ComponentDescriptorProviderRegistry> registry) {
  registry->add(
      concreteComponentDescriptorProvider<ObsidianVideoComponentDescriptor>());
}

} // namespace facebook::react

#endif // __has_include(ComponentDescriptors.h)

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
  return facebook::jni::initialize(vm, [] {});
}
